export interface CONTRATO {
    createdAt: string,
    updatedAt: string,
    id: string,
    cantidad: number,
    total: number,
    subtotal: number,
    estado: string,
    ciudad: string,
    codigo: string,
    codigoglobal: string,
    valorentrega: number,
    fechaentrega: string,
    fechamaxima: string,
    costoenvio: number,
    pais: string,
    provivencia: string,
    direccion1: string,
    direccion2: string,
    descuento: 0,
    codigopostal: string,
    terminocondicione: boolean,
    suscribete: boolean,
};