export interface NAMEAPP {
    app: String;
    logo: String;
    descripcion: String;
    nit: String;
    direccion: String;
    telefono: String;
    email: String;
    portada1: String;
    portada2: String; 
    portada3: String;
    portada4: String;
    portada5: String;
    politicas: String;
    apoyo1: String;
    apoyo2: String;
    apoyo3: String;
    apoyo4: String;
    apoyo5: String;
    apoyo6: String;
};